### PR TITLE
[CQ Award] Switched to using geojson for the map

### PR DESCRIPTION
**Pull request by AndreasK79**
Finally figured out using geoJson for the CQ map:
image

### CODE REVIEW

**Review by HB9HIL — APPROVED** [review]
working nice :) thx for that

**Review by HB9HIL — CHANGES_REQUESTED** [review]
but wouldn't it be better to outsource the big big json stuff to another file?..

**Comment by AndreasK79** [comment]
@HB9HIL adjusted the code to load geojson from its own file.

**Review by HB9HIL — APPROVED** [review]
works great :) thx

**Pull request merged**
