### PR TITLE
Fix racecondition at contesting

### PR DESCRIPTION
**Pull request by int2001**
Racecondition occures at "Start new contest-Session", where setSession can be called before deleteSession is called/finished.

### CODE REVIEW

**Comment by HB9HIL** [comment]
contesting

I created a new session, chose the contest and started logging

But no QSO's in Table

had to reload the page with F5 in order to see the QSO in the table. After that it worked. Don't know if this is related to your code or something different. 

Then I started a new Session, chose ANOTHER contest and started logging again ONE QSO:

contest2

It shows the QSO from the previous logging session. But the the QSO I logged in the new session (DJ9NT)

**Review by HB9HIL — CHANGES_REQUESTED** [review]
there is also something else

**Comment by AndreasK79** [comment]
Session stuff seems to work at least, but haven't looked into the previous QSO stuff.

**Comment by HB9HIL** [comment]
> Session stuff seems to work at least, but haven't looked into the previous QSO stuff.

so seems like another issue not related to this PR? The we can merge this one and check the other stuff later

**Review by HB9HIL — APPROVED** [review]

**Comment by int2001** [comment]
> Session stuff seems to work at least, but haven't looked into the previous QSO stuff.

This one only heals the racecondition. Not more.
We know: there is much more

**Pull request merged**
